### ISSUE TITLE
Unable to set visibility for file

### ISSUE THREAD

**Issue by ashu1409** [odan/twig-assets#33]
An exception has been thrown during the rendering of a template:

`Unable to set visibility for file minified_javascript_core_fca972a47fddc27c98d276c1370ebabe.js. chmod(): Operation not permitted`.

**Comment by odan** [comment]
The error message suggests that the script is unable to set the visibility of the file because the operation is not permitted. This can happen when there is a permission issue with the file or directory where the file is located.

Here are some steps you can take to resolve this issue:

* Check the permissions. Make sure that the user or group that the web server is running under has the necessary permissions to access and modify the file.

* Try setting the permissions using the chmod command. 

* If you are using a shared hosting service, contact your hosting provider to check if there are any restrictions on modifying file permissions.
