### ISSUE TITLE
Is there any way to configure the public path?

### ISSUE THREAD

**Issue by dev-rfc** [odan/twig-assets#5]
Hello again :)

I am working on a multi module application, which have a shared assets folder. This is my folder structure for public directory

```
www
     assets: shared assets for all modules
     +semantic-ui.css
     +custom.css
     auth: auth module
     + index.php - auth module loader
     finances:
     + index.php - finances module loader
```

When the user hits /finances/{controller}/{method}/{args}, everything is redirected to /finances/index.php, which load a shared source code (using Slim Framework 3). This setup works fine since the application is completely modular, but there is a problem when using twig-assets extension.

Here my settings:

```php
$options = 
[
    'path' => '/var/www/app/htdocs/public/assets/cache',
    'path_chmod' => -1,
    'cache_enabled' => true,
    'cache_path' => '/var/www/app/htdocs/temp',
    'cache_name' => 'assets-cache',
    'cache_lifetime' => 0,
    'minify' => 1
];
```
And the assets code:

{{ assets({files: [
    '@public/semantic-ui.css',
    '@public/custom.css',
    ], name: 'bundle.css'})
}}

The problem is that assets code generate a URL referencing the current folder, which in that case will be the modules folder (eg: finances), not shared assets. This is the expected behavior, not a bug, but in my case i want to customize this path.

Generated URL: cache/bundle.{hash}.css

I wanted to set the generated URL manually to /assets/cache/bundle.{hash}.css.

Is there a way to do this?

Eg: This could solve the problem:

```
{{ assets({files: [
    '@public/semantic-ui.css',
    '@public/custom.css',
    ], name: 'bundle.css', base_path: '/assets/'})
}}
```
or

```php
$options = 
[
    'base_path' => '/assets/',
];
```

What do you think about this?

Thank you.

**Comment by odan** [comment]
Hi!

Maybe the path and filename could be just added to the `name` parameter:

```twig
{{ assets({files: [
    '@public/semantic-ui.css',
    '@public/custom.css',
    ], name: 'assets/bundle.css'})
}}
```

**Comment by ghost** [comment]
Hi!

We have the same problem. We have tried with the name paramter but doesn't work. Actually what @renancavalieri said it is a good idea and can solve more problems. 

Another problem with the code that, it is return with the following line:

`<link rel="stylesheet" type="text/css" href="dir/bundle.min.{hash}.css" media="all" />`

And missing the slash character from the beginning of the url. Therefore can't find the directory and the file if we put it on the root folder.

Thank you for your answer.

**Comment by odan** [comment]
I always set the base path in my HTML layout template like this:

### Slim Twig example:

```twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <!-- other stuff -->
    <base href="{{ base_url() }}/"/>
    <!-- other stuff -->
```
[Full example](https://github.com/odan/prisma/blob/master/templates/Layout/layout.twig#L10)

Then you don't need to pass a path, because the browser will load the correct url according to `base href`. Please try this first.

**Comment by ghost** [comment]
Thank you, it is a really useful stuff, but actually first we would like to put the assets files in another folder like: root/assets/min.
We try to fix it with a base_path params and send it in a pull request in a few days, if you don't mind.

**Comment by odan** [comment]
Maybe I don't get it. Why don't you use the `path` setting to configure the public path?

```php
 // Public assets cache directory
'path' => '/var/www/app/htdocs/public/assets',
```
or whatever you want :-)

```php
 // Public assets cache directory
'path' => '/root/assets/min',
```

**Comment by ghost** [comment]
Actually we have tried. We have a cache directory like root/dir/assets/min, what we set up in the config file.
It's fine because the generated css is here: root/dir/assets/min/layout{hash}.min.css
But the createCacheBustedUrl method in the PublicAssetsCache class return just the last dir, therefore in the return string of the css method will be this:
`<link rel="stylesheet" type="text/css" href="min/bundle.min.{hash}.css" media="all" />`
instead of
`<link rel="stylesheet" type="text/css" href="/dir/assets/min/bundle.min.{hash}.css" media="all" />`

Yes maybe we can set up the base path in the head but not all of assets in this directory. So we can't   set this globally.

[edit]
And if we set up the global base path to dir/assets, then it maybe can confuse the mod_rewrite urls.

**Comment by odan** [comment]
Ok you can create a PR :-)

**Comment by odan** [comment]
Ok, everything is merged and available in v.2.0.0.

The `path` option is now separated from the public url. You just have to change the correct `path` and `url_base_path` after updating to v2. Also don't forget to clear the internal and public cache.

**Comment by dev-rfc** [comment]
Thank you! I will test it soon!

:)
